version: "2"
run:
  modules-download-mode: readonly
  timeout: 5m
  concurrency: 8

linters:
  enable:
    - gocritic
    - mirror
  settings:
    gocritic:
      disable-all: false
    staticcheck:
      checks:
        - all

issues:
  max-same-issues: 0
  exclusions:
    generated: lax
    paths:
      - vendor$
      - third_party$
      - internal/c_api$
      - examples/experimental$
    rules:
      - linters:
          - staticcheck
        text: 'ST1003: should not use underscores in Go names'
      - path: examples/experimental/main.go
        text: "possible misuse of unsafe.Pointer"