version: "2"
run:
  modules-download-mode: readonly
  timeout: 5m
  concurrency: 8

linters:
  enable:
    - gocritic
    - mirror
  settings:
    gocritic:
      disable-all: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'ST1003: should not use underscores in Go names'
      - linters:
          - govet
        path: examples/experimental/main\.go
        text: "possible misuse of unsafe.Pointer"
      - linters:
          - errcheck
        path: examples/experimental/
        text: "Error return value"
    paths:
      - third_party$
      - internal/c_api$
      - examples/experimental$

issues:
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - internal/c_api$
      - examples/experimental$